package amb_java.swing;




import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

/**
 * @author Laurier HABIYAREMYE - Greens Laurier Master With certified Copyright.
 */
public class ReportsAndAnalyticsForm extends JFrame {
    private static final long serialVersionUID = 1L;
    private JPanel contentPane;
    private JComboBox<String> reportTypeComboBox;
    private JTextField dateRange;
    private JTextField generatedBy;
   
    private JTextArea reportContent;
    private JButton btnNewButton;



    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ReportsAndAnalyticsForm frame = new ReportsAndAnalyticsForm();
                    frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }



    public ReportsAndAnalyticsForm() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\User\\Desktop\\STDM.jpg"));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("...                                                                          REPORTS AND ANALYTICS PAGE                         (AMBULANCE  BOOKING  SYSTEM )                 ...");
        setBounds(180, 50, 1014, 597);
        setResizable(true);
        contentPane = new JPanel();
        contentPane.setBackground(new Color(176, 196, 222));
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
        setContentPane(contentPane);
        contentPane.setLayout(null);

        JLabel lblNewAmbulanceRegister = new JLabel("REPORTS AND ANALYTICS");
        lblNewAmbulanceRegister.setFont(new Font("Bernard MT Condensed", Font.PLAIN, 32));
        lblNewAmbulanceRegister.setForeground(new Color(0, 0, 128)); 
        lblNewAmbulanceRegister.setBounds(362, 25, 325, 50);
        contentPane.add(lblNewAmbulanceRegister);

        JLabel lblReportType = new JLabel("Report Type");
        lblReportType.setFont(new Font("Goudy Old Style", Font.BOLD, 18));
        lblReportType.setBounds(58, 151, 99, 43);
        contentPane.add(lblReportType);

        JLabel lblDateRange = new JLabel("Date");
        lblDateRange.setFont(new Font("Goudy Old Style", Font.BOLD, 18));
        lblDateRange.setBounds(58, 270, 110, 29);
        contentPane.add(lblDateRange);

        JLabel lblGeneratedBy = new JLabel("Generated By");
        lblGeneratedBy.setFont(new Font("Goudy Old Style", Font.BOLD, 18));
        lblGeneratedBy.setBounds(542, 151, 124, 36);
        contentPane.add(lblGeneratedBy);
        
       

        reportTypeComboBox = new JComboBox<>(new String[]{"Trip Report", "Ambulance Report", "Payment Report", "System Analytics Report", "Incident Report","Monthly/Yearly Report","Compliance Report"});
        reportTypeComboBox.setFont(new Font("Goudy Old Style", Font.PLAIN, 18));
        reportTypeComboBox.setBounds(214, 151, 228, 50);
        contentPane.add(reportTypeComboBox);

        dateRange = new JTextField();
        dateRange.setFont(new Font("Bookman Old Style", Font.PLAIN, 12));
        dateRange.setBounds(214, 270, 228, 50);
        contentPane.add(dateRange);
        dateRange.setColumns(10);

        generatedBy = new JTextField();
        generatedBy.setFont(new Font("Bookman Old Style", Font.PLAIN, 12));
        generatedBy.setBounds(707, 151, 228, 50);
        contentPane.add(generatedBy);
        generatedBy.setColumns(10);
        
        

        JLabel lblreportContent = new JLabel("Report Content");
        lblreportContent.setFont(new Font("Goudy Old Style", Font.BOLD, 18));
        lblreportContent.setBounds(542, 270, 99, 29);
        contentPane.add(lblreportContent);
        
        
       
        reportContent = new JTextArea("Enter your report content here");
        reportContent.setFont(new Font("Bookman Old Style", Font.PLAIN, 15));
        reportContent.setBounds(707, 270, 228, 150);
        contentPane.add(reportContent);
        
        reportContent.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if ("Enter your report content here".equals(reportContent.getText())) {
                    reportContent.setText("");
                    reportContent.setForeground(Color.BLACK); 
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (reportContent.getText().isEmpty()) {
                    reportContent.setText("Enter your report content here");
                    reportContent.setForeground(Color.GRAY); 
                }
            }
        });


        reportContent.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if ("Enter your report content here".equals(reportContent.getText())) {
                    reportContent.setText("");
                    reportContent.setForeground(Color.BLACK); 
                }
            }
        });


        reportContent.setForeground(Color.GRAY); 

        
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = currentDateTime.format(formatter);
        dateRange.setText(formattedDateTime);
       
        
        reportTypeComboBox.setBackground(Color.LIGHT_GRAY);
        dateRange.setBackground(Color.LIGHT_GRAY);
        generatedBy.setBackground(Color.LIGHT_GRAY);
        reportContent.setBackground(Color.LIGHT_GRAY);
        


        btnNewButton = new JButton("Submit");
        btnNewButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Object ReportType = reportTypeComboBox.getSelectedItem();
                String DateRange = dateRange.getText();
                String GeneratedBy = generatedBy.getText();
                String ReportContent = reportContent.getText();
                String msg = "" + ReportType;
                msg += " 0012";
              

                try {
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:4306/habiyaremye_laurier_abs", "222003068", "222003068");

                    String query = "INSERT INTO reportsandanalytics (ReportType, DateRange, GeneratedBy, ReportContent) " +
                            "VALUES ('" + ReportType + "','" + DateRange + "','" + GeneratedBy + "','" + ReportContent + "')";

                    
                    Statement sta = connection.createStatement();
                    int x = sta.executeUpdate(query);
                    if (x == 0) {
                        JOptionPane.showMessageDialog(btnNewButton, "An Error occured during submission");
                    } else {
                        JOptionPane.showMessageDialog(btnNewButton,
                            "Report in : " + msg + " Classification was sucessfully submitted");
                    }
                    connection.close();
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
            }
        });
        btnNewButton.setFont(new Font("Algerian", Font.PLAIN, 22));
        btnNewButton.setBounds(460, 460, 180, 62);
        btnNewButton.setBackground(new Color(139, 0, 0));
        btnNewButton.setForeground(Color.WHITE); 
        contentPane.add(btnNewButton);
        
        JLabel copyrightLabel = new JLabel("\u00a9 2024 Laurier HABIYAREMYE - ABS(Ambulance Booking System) . All rights reserved.");
        copyrightLabel.setForeground(Color.GRAY);
        copyrightLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
        copyrightLabel.setHorizontalAlignment(SwingConstants.CENTER);
        copyrightLabel.setBounds(10, 530, 974, 20); 
        contentPane.add(copyrightLabel);
    }
}

